import { auditApi } from "@/lib/api/audit.api";
import { ExecutiveSummaryCard } from "@/components/audit/ExecutiveSummaryCard";
import { SavingsKpiCards } from "@/components/audit/SavingsKpiCards";
import { SpendComparisonCharts } from "@/components/audit/SpendComparisonCharts";
import { ToolRecommendationsTable } from "@/components/audit/ToolRecommendationsTable";
import { ShieldCheck, Sparkles } from "lucide-react";
import Link from "next/link";

import type { Metadata } from "next";

// Server Component for native SEO and shareable metadata
export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const resolvedParams = await params;
  let savingsText =
    "Defensible AI spend and cloud architecture audit. Verified monthly/annual savings recommendations and executive synthesis.";
  let title = `Argus Executive Audit Report — #${resolvedParams.slug}`;

  try {
    const report = await auditApi.getAuditBySlug(resolvedParams.slug);
    if (report) {
      title = `Argus Executive Audit Report (${report.teamSize} Seats) — $${report.totalMonthlySavings}/mo Identified Savings`;
      savingsText = `Verified analysis across ${report.items?.length || 0} AI tools. Annualized bottom-line impact of $${report.totalAnnualSavings}/yr. Executive synthesis and tier recommendations inside.`;
    }
  } catch {
    // Fallback if API offline or report not found during metadata generation
  }

  return {
    title,
    description: savingsText,
    openGraph: {
      title,
      description: savingsText,
      url: process.env.NEXT_PUBLIC_SITE_URL + `/share/${resolvedParams.slug}`,
      siteName: "Argus AI Architecture Auditor by TechVruk",
      type: "article",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description: savingsText,
    },
  };
}

export default async function SharedSlugPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const resolvedParams = await params;
  let auditReport = null;
  let error = null;

  try {
    auditReport = await auditApi.getAuditBySlug(resolvedParams.slug);
  } catch (err: any) {
    error = err.message || "Could not retrieve shared report.";
  }

  if (error || !auditReport) {
    return (
      <div className="min-h-screen bg-[#060a12] flex flex-col items-center justify-center p-8 text-center space-y-4 animate-fade-in-up">
        <h2 className="text-2xl font-bold text-white">Report Not Found</h2>
        <p className="text-sm text-zinc-500 max-w-md">
          {error || `No public report found for slug: ${resolvedParams.slug}`}
        </p>
        <Link
          href="/"
          className="px-6 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-semibold text-sm transition-all"
        >
          Run New AI Spend Audit
        </Link>
      </div>
    );
  }

  const totalCurrentMonthlySpend = auditReport.items.reduce(
    (sum, t) => sum + (Number(t.currentSpend) || 0),
    0,
  );

  return (
    <div className="min-h-screen bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-zinc-900 via-[#060a12] to-black py-12 px-4 sm:px-6 lg:px-8 space-y-10">
      {/* Top Banner */}
      <div className="max-w-6xl mx-auto p-4 rounded-2xl bg-gradient-to-r from-emerald-500/8 via-teal-500/8 to-violet-500/8 border border-emerald-500/20 flex flex-col sm:flex-row sm:items-center justify-between gap-4 animate-fade-in-up">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-xl bg-emerald-500/10 text-emerald-400">
            <Sparkles className="w-5 h-5" />
          </div>
          <div>
            <h4 className="text-sm font-bold text-white">
              Public Shareable Executive Report
            </h4>
            <p className="text-xs text-zinc-400">
              Generated by Argus AI Architecture Auditor for Team Size:{" "}
              {auditReport.teamSize} seats ({auditReport.primaryUseCase})
            </p>
          </div>
        </div>
        <Link
          href="/"
          className="px-5 py-2 rounded-xl glass-card hover:bg-white/[0.04] text-white text-xs font-semibold text-center shrink-0 transition-all"
        >
          Run Your Own Stack Audit &rarr;
        </Link>
      </div>

      {/* Header */}
      <div className="max-w-6xl mx-auto flex items-center justify-between border-b border-white/6 pb-6 animate-fade-in-up animate-delay-100">
        <div className="space-y-1">
          <div className="flex items-center gap-3">
            <span className="font-heading font-bold tracking-[0.1em] text-xl bg-gradient-to-b from-white via-emerald-100 to-emerald-400 bg-clip-text text-transparent select-none">
              ARGUS
            </span>
            <div className="h-5 w-px bg-white/10" />
            <h1 className="text-xl sm:text-2xl font-bold text-white">
              AI Spend Optimization Report
            </h1>
          </div>
          <p className="text-sm text-zinc-500">
            Report Reference ID: {auditReport.shareSlug} &bull; Prepared on{" "}
            {new Date(auditReport.createdAt).toLocaleDateString()}
          </p>
        </div>
      </div>

      {/* Sections */}
      <div className="max-w-6xl mx-auto space-y-10">
        <div className="animate-fade-in-up animate-delay-200">
          <ExecutiveSummaryCard summaryParagraph={auditReport.summaryParagraph} />
        </div>

        <div className="animate-fade-in-up animate-delay-300">
          <SavingsKpiCards
            totalMonthlySavings={auditReport.totalMonthlySavings}
            totalAnnualSavings={auditReport.totalAnnualSavings}
            overallStatus={auditReport.overallStatus}
            totalCurrentMonthlySpend={totalCurrentMonthlySpend}
          />
        </div>

        <div className="animate-fade-in-up animate-delay-400">
          <SpendComparisonCharts toolBreakdowns={auditReport.items} />
        </div>

        <div className="animate-fade-in-up animate-delay-500">
          <ToolRecommendationsTable toolBreakdowns={auditReport.items} />
        </div>
      </div>

      {/* Footer */}
      <footer className="max-w-6xl mx-auto pt-12 pb-8 border-t border-white/5 text-center text-xs text-zinc-600 space-y-1 animate-fade-in-up animate-delay-500">
        <p>
          Argus AI Architectural Audit Engine &bull; Defensible Spend
          Optimization
        </p>
      </footer>
    </div>
  );
}
