import { auditApi } from "@/lib/api/audit.api";
import { ExecutiveSummaryCard } from "@/components/audit/ExecutiveSummaryCard";
import { SavingsKpiCards } from "@/components/audit/SavingsKpiCards";
import { SpendComparisonCharts } from "@/components/audit/SpendComparisonCharts";
import { ToolRecommendationsTable } from "@/components/audit/ToolRecommendationsTable";
import { ShieldCheck, Sparkles } from "lucide-react";
import Link from "next/link";

// Server Component for native SEO and shareable metadata
export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const resolvedParams = await params;
  return {
    title: `Argus Executive Audit Report — #${resolvedParams.slug}`,
    description:
      "Defensible AI spend and cloud architecture audit. Verified monthly/annual savings recommendations and executive synthesis.",
  };
}

export default async function SharedSlugPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const resolvedParams = await params;
  let auditReport = null;
  let error = null;

  try {
    auditReport = await auditApi.getAuditBySlug(resolvedParams.slug);
  } catch (err: any) {
    error = err.message || "Could not retrieve shared report.";
  }

  if (error || !auditReport) {
    return (
      <div className="min-h-screen bg-[#090d16] flex flex-col items-center justify-center p-8 text-center space-y-4">
        <h2 className="text-2xl font-bold text-white">Report Not Found</h2>
        <p className="text-sm text-zinc-400 max-w-md">
          {error || `No public report found for slug: ${resolvedParams.slug}`}
        </p>
        <Link
          href="/"
          className="px-6 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-semibold text-sm transition-all"
        >
          Run New AI Spend Audit
        </Link>
      </div>
    );
  }

  const totalCurrentMonthlySpend = auditReport.items.reduce(
    (sum, t) => sum + (Number(t.currentSpend) || 0),
    0,
  );

  return (
    <div className="min-h-screen bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-zinc-900 via-[#090d16] to-black py-12 px-4 sm:px-6 lg:px-8 space-y-10">
      {/* Top Banner */}
      <div className="max-w-6xl mx-auto p-4 rounded-2xl bg-gradient-to-r from-emerald-500/15 via-teal-500/15 to-violet-500/15 border border-emerald-500/30 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-xl bg-emerald-500/20 text-emerald-400">
            <Sparkles className="w-5 h-5" />
          </div>
          <div>
            <h4 className="text-sm font-bold text-white">
              Public Shareable Executive Report
            </h4>
            <p className="text-xs text-zinc-300">
              Generated by Argus AI Architecture Auditor for Team Size:{" "}
              {auditReport.teamSize} seats ({auditReport.primaryUseCase})
            </p>
          </div>
        </div>
        <Link
          href="/"
          className="px-5 py-2 rounded-xl bg-zinc-900 hover:bg-zinc-800 text-white border border-zinc-700 text-xs font-semibold text-center shrink-0 transition-all"
        >
          Run Your Own Stack Audit &rarr;
        </Link>
      </div>

      {/* Header */}
      <div className="max-w-6xl mx-auto flex items-center justify-between border-b border-zinc-800/80 pb-6">
        <div className="space-y-1">
          <h1 className="text-2xl sm:text-3xl font-extrabold text-white flex items-center gap-2.5">
            <ShieldCheck className="w-7 h-7 text-emerald-400" />
            AI Spend Optimization Report
          </h1>
          <p className="text-sm text-zinc-400">
            Report Reference ID: {auditReport.shareSlug} &bull; Prepared on{" "}
            {new Date(auditReport.createdAt).toLocaleDateString()}
          </p>
        </div>
      </div>

      {/* Sections */}
      <div className="max-w-6xl mx-auto space-y-10">
        <ExecutiveSummaryCard summaryParagraph={auditReport.summaryParagraph} />

        <SavingsKpiCards
          totalMonthlySavings={auditReport.totalMonthlySavings}
          totalAnnualSavings={auditReport.totalAnnualSavings}
          overallStatus={auditReport.overallStatus}
          totalCurrentMonthlySpend={totalCurrentMonthlySpend}
        />

        <SpendComparisonCharts toolBreakdowns={auditReport.items} />

        <ToolRecommendationsTable toolBreakdowns={auditReport.items} />
      </div>

      {/* Footer */}
      <footer className="max-w-6xl mx-auto pt-12 pb-8 border-t border-zinc-800/60 text-center text-xs text-zinc-500 space-y-1">
        <p>
          Argus AI Architectural Audit Engine &bull; Defensible Spend
          Optimization
        </p>
      </footer>
    </div>
  );
}
